name: tests
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter test
